### ISSUE TITLE
JsonLines 

### ISSUE THREAD

**Issue by benjaminsims** [pabloem/beam_utils#1]
I had some trouble using the JSONLinesFileSource; it was hanging when trying to process a large file and processing smaller files unpredictably.

After having a look at the source, I realised that JSONLinesFileSource is designed to process streaming JSON where all of the objects are on one line, using a buffer. JSONLines is a format where each object is on a separate line (http://jsonlines.org).

It might be a good idea to rename the Source in order to avoid this confusion?

**Comment by pabloem** [comment]
I intended to make a jsonlines source. I see that I did not test it properly. Apologies. I'll fix that asap.
-P.

**Comment by pabloem** [comment]
I tested it with a small test case, and found no issues. Are, perhaps, your per-line JSON objects very very large? Can you provide an example file so that I can reproduce the problem?

**Comment by benjaminsims** [comment]
Thanks Pablo. I created a test file:
https://gist.github.com/benjaminsims/be9791259f0ce2b5c8c14d30a8956291

The test script is:

https://gist.github.com/benjaminsims/22e6ad10d322b889f7dbbfa73b5f229c

This contains 10,000 random words in JSON objects. When I run it locally, the processing only gets as far as line 3688. Adding or removing lines previous to that point will change the point at which processing fails but not in a predictable way, which makes me think it may be do with buffer size?

On a side note, is it correct to say that JSONLines files are not splittable? I'm too new to Beam to know how much of a performance difference it makes, but we use them specifically because they can be split and parallel processed.

**Comment by pabloem** [comment]
Thanks for the sample, Benjamin! The bug is a corner case related to the stripping of the new lines, and the buffering of the file. I'm pushing the fix now.

Regarding the splitting, I need to check how to implement the splitting logic; but as long as it's possible to split on new lines (which I think it is), we should be fine. Give me another week to try to get out a split routine for this.

**Comment by benjaminsims** [comment]
Thanks for the quick fix Pablo, much appreciated. 

The format officially splits on '\n'. The reason I'd thought you were targeting files with all the objects on one line was the reference in the code to http://stackoverflow.com/questions/21708192/how-do-i-use-the-json-module-to-read-in-one-json-object-at-a-time/, which is specific to that use case.

With a valid file separated by newlines, I'm not sure if using a buffer has advantages over just reading the lines?

**Comment by pabloem** [comment]
I see your point. I had originally used that code because I thought that JSON objects did not need to escape the newline character within strings (e.g. a json string could contain newlines), and just reading line by line would fall into this trap; but seeing that strings in json do have to escape the newline, it should be possible to just read line by line and decode that.
I guess I over-engineered the source : )
I'll push this simplification later today then.

**Comment by pabloem** [comment]
I pushed the simplification.
